inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - vendor/ruby/**/*
    - node_modules/**/*
    - .licenses/**/*
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - db/migrate/*
    - config/environments/*
    - lib/tasks/**/*
    - spec/**/*
Style/Documentation:
  Enabled: false
