name: Containerize

on:
  push:
    branches: [ main ]

env:
  RUBY_VERSION: '2.7.6'
  RAILS_ENV: production

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      sha-tag: ${{ fromJSON(steps.meta.outputs.json).labels['deploy-tag'] }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::609231472294:role/cinema-bot-ric_role@github_actions
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR Public
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Log in to the GitHub package
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ steps.login-ecr.outputs.registry }}/cinema-bot-ric
          ghcr.io/${{ github.repository }}
        labels: |
            deploy-tag=sha-{{sha}}
        tags: |
          type=sha
          type=ref,event=branch

    - name: Add short SHA information
      id: commit
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        build-args: |
            REVISION=${{ steps.commit.outputs.sha_short }}

  trigger-deployment:
    needs: build-and-push-image
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deployment.yml
    with:
      version: ${{ needs.build-and-push-image.outputs.sha-tag }}
    secrets: inherit
